CREATE TABLE "scheduled_tasks" (
	"uuid" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"task_type" text NOT NULL,
	"task_payload" jsonb NOT NULL,
	"cron_expression" text NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"concurrency_mode" text DEFAULT 'skip' NOT NULL,
	"max_concurrent_executions" integer DEFAULT 1 NOT NULL,
	"max_executions_per_day" integer,
	"min_credits_required" integer DEFAULT 100 NOT NULL,
	"auto_pause_on_low_credits" boolean DEFAULT true NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_paused" boolean DEFAULT false NOT NULL,
	"pause_reason" text,
	"last_execution_at" timestamp with time zone,
	"next_execution_at" timestamp with time zone,
	"total_executions" integer DEFAULT 0 NOT NULL,
	"successful_executions" integer DEFAULT 0 NOT NULL,
	"failed_executions" integer DEFAULT 0 NOT NULL,
	"consecutive_failures" integer DEFAULT 0 NOT NULL,
	"tags" jsonb,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "task_executions" (
	"uuid" uuid PRIMARY KEY NOT NULL,
	"scheduled_task_uuid" uuid NOT NULL,
	"execution_number" integer NOT NULL,
	"idempotency_key" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"duration_ms" integer,
	"job_uuid" uuid,
	"credits_used" integer DEFAULT 0 NOT NULL,
	"items_processed" integer DEFAULT 0 NOT NULL,
	"items_succeeded" integer DEFAULT 0 NOT NULL,
	"items_failed" integer DEFAULT 0 NOT NULL,
	"error_message" text,
	"error_code" text,
	"error_details" jsonb,
	"triggered_by" text DEFAULT 'scheduler' NOT NULL,
	"scheduled_for" timestamp with time zone NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "task_executions_idempotency_key_unique" UNIQUE("idempotency_key")
);
--> statement-breakpoint
CREATE TABLE "webhook_deliveries" (
	"uuid" uuid PRIMARY KEY NOT NULL,
	"webhook_subscription_uuid" uuid NOT NULL,
	"event_type" text NOT NULL,
	"event_source" text NOT NULL,
	"event_source_id" uuid NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempt_number" integer DEFAULT 1 NOT NULL,
	"max_attempts" integer DEFAULT 3 NOT NULL,
	"request_url" text NOT NULL,
	"request_method" text DEFAULT 'POST' NOT NULL,
	"request_headers" jsonb,
	"request_body" jsonb,
	"response_status" integer,
	"response_headers" jsonb,
	"response_body" text,
	"response_duration_ms" integer,
	"error_message" text,
	"error_code" text,
	"next_retry_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"delivered_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "webhook_subscriptions" (
	"uuid" uuid PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"webhook_url" text NOT NULL,
	"webhook_secret" text NOT NULL,
	"scope" text DEFAULT 'all' NOT NULL,
	"specific_task_ids" jsonb,
	"event_types" jsonb NOT NULL,
	"custom_headers" jsonb,
	"timeout_seconds" integer DEFAULT 10 NOT NULL,
	"max_retries" integer DEFAULT 3 NOT NULL,
	"retry_backoff_multiplier" real DEFAULT 2 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"consecutive_failures" integer DEFAULT 0 NOT NULL,
	"auto_disable_after_failures" integer DEFAULT 10 NOT NULL,
	"last_success_at" timestamp with time zone,
	"last_failure_at" timestamp with time zone,
	"total_deliveries" integer DEFAULT 0 NOT NULL,
	"successful_deliveries" integer DEFAULT 0 NOT NULL,
	"failed_deliveries" integer DEFAULT 0 NOT NULL,
	"tags" jsonb,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "task_executions" ADD CONSTRAINT "task_executions_scheduled_task_uuid_scheduled_tasks_uuid_fk" FOREIGN KEY ("scheduled_task_uuid") REFERENCES "public"."scheduled_tasks"("uuid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task_executions" ADD CONSTRAINT "task_executions_job_uuid_jobs_uuid_fk" FOREIGN KEY ("job_uuid") REFERENCES "public"."jobs"("uuid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_webhook_subscription_uuid_webhook_subscriptions_uuid_fk" FOREIGN KEY ("webhook_subscription_uuid") REFERENCES "public"."webhook_subscriptions"("uuid") ON DELETE cascade ON UPDATE no action;