CREATE TABLE `scheduled_tasks` (
	`uuid` text PRIMARY KEY NOT NULL,
	`api_key_id` text,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`task_type` text NOT NULL,
	`task_payload` text NOT NULL,
	`cron_expression` text NOT NULL,
	`timezone` text DEFAULT 'UTC' NOT NULL,
	`concurrency_mode` text DEFAULT 'skip' NOT NULL,
	`max_executions_per_day` integer,
	`min_credits_required` integer DEFAULT 1 NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`is_paused` integer DEFAULT false NOT NULL,
	`pause_reason` text,
	`last_execution_at` integer,
	`next_execution_at` integer,
	`total_executions` integer DEFAULT 0 NOT NULL,
	`successful_executions` integer DEFAULT 0 NOT NULL,
	`failed_executions` integer DEFAULT 0 NOT NULL,
	`consecutive_failures` integer DEFAULT 0 NOT NULL,
	`tags` text,
	`metadata` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`api_key_id`) REFERENCES `api_key`(`uuid`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `task_executions` (
	`uuid` text PRIMARY KEY NOT NULL,
	`scheduled_task_uuid` text NOT NULL,
	`execution_number` integer NOT NULL,
	`idempotency_key` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`started_at` integer,
	`completed_at` integer,
	`duration_ms` integer,
	`job_uuid` text,
	`credits_used` integer DEFAULT 0 NOT NULL,
	`items_processed` integer DEFAULT 0 NOT NULL,
	`items_succeeded` integer DEFAULT 0 NOT NULL,
	`items_failed` integer DEFAULT 0 NOT NULL,
	`error_message` text,
	`error_code` text,
	`error_details` text,
	`triggered_by` text DEFAULT 'scheduler' NOT NULL,
	`scheduled_for` integer NOT NULL,
	`metadata` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`scheduled_task_uuid`) REFERENCES `scheduled_tasks`(`uuid`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`job_uuid`) REFERENCES `jobs`(`uuid`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `task_executions_idempotency_key_unique` ON `task_executions` (`idempotency_key`);--> statement-breakpoint
CREATE TABLE `webhook_deliveries` (
	`uuid` text PRIMARY KEY NOT NULL,
	`webhook_subscription_uuid` text NOT NULL,
	`event_type` text NOT NULL,
	`event_source` text NOT NULL,
	`event_source_id` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`attempt_number` integer DEFAULT 1 NOT NULL,
	`max_attempts` integer DEFAULT 3 NOT NULL,
	`request_url` text NOT NULL,
	`request_method` text DEFAULT 'POST' NOT NULL,
	`request_headers` text,
	`request_body` text,
	`response_status` integer,
	`response_headers` text,
	`response_body` text,
	`response_duration_ms` integer,
	`error_message` text,
	`error_code` text,
	`next_retry_at` integer,
	`created_at` integer NOT NULL,
	`delivered_at` integer,
	FOREIGN KEY (`webhook_subscription_uuid`) REFERENCES `webhook_subscriptions`(`uuid`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `webhook_subscriptions` (
	`uuid` text PRIMARY KEY NOT NULL,
	`api_key_id` text,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`webhook_url` text NOT NULL,
	`webhook_secret` text NOT NULL,
	`scope` text DEFAULT 'all' NOT NULL,
	`specific_task_ids` text,
	`event_types` text NOT NULL,
	`custom_headers` text,
	`timeout_seconds` integer DEFAULT 10 NOT NULL,
	`max_retries` integer DEFAULT 3 NOT NULL,
	`retry_backoff_multiplier` real DEFAULT 2 NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`consecutive_failures` integer DEFAULT 0 NOT NULL,
	`auto_disable_after_failures` integer DEFAULT 10 NOT NULL,
	`last_success_at` integer,
	`last_failure_at` integer,
	`total_deliveries` integer DEFAULT 0 NOT NULL,
	`successful_deliveries` integer DEFAULT 0 NOT NULL,
	`failed_deliveries` integer DEFAULT 0 NOT NULL,
	`tags` text,
	`metadata` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`api_key_id`) REFERENCES `api_key`(`uuid`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
ALTER TABLE `jobs` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `request_log` ADD `user_id` text;--> statement-breakpoint
ALTER TABLE `template_executions` ADD `user_id` text;